### PR TITLE
Replace KEY_BACKSPACE by a list

### PR DESCRIPTION
**Pull request by PabloLec**
This PR tries to solve #74.
Currently the `KEY_BACKSPACE` var is set either explicitly if win32 or darwin, or else by curses.
The thing is curses might get a wrong backspace key on Linux depending on `$TERM` environment variable value and actual terminal conf.

To solve this issue, we might just catch as a backspace all possible values. Either `8` (ASCII BS), `127` (ASCII DEL) and any other value returned by `curses.KEY_BACKSPACE`.  
This shouldn't cause any false positive as `8` and `127` are well defined, except if a user explicitly tweaked his terminal configuration for  `8` and `127` which would cause trouble with curses anyway. 

- [x] I have read the contribution guidelines
- [x] CI Unit tests pass
- [x] New functions/classes have consistent docstrings

**What this pull request changes**

- `KEY_BACKSPACE` is now a list `KEYS_BACKSPACE`.
- And some auto deletion of useless white spaces, well, better now than never.

**Issues fixed with this pull request**

* #74 

**Optionally, what changes should join this PR**

If this solution is accepted, I will need to edit docs reference of `KEY_BACKSPACE`.

### CODE REVIEW

**Review by jwlodek — CHANGES_REQUESTED** [review]
This is a good solution to this problem, however, we still need to handle the possibility of the user wanting to create his/her own key_command with the backspace key. In that case, I think the easiest solution actually will be in the `add_key_command` function, just add an individual key-command entry into the dict for each of the values in the list. So something like:

```
if key == py_cui.keys.KEY_BACKSPACE:
    for bcksp_key in key:
        self._key_commands[bcksp_key] = command
else:
    self._key_commands[key] = command
```

Or even better would be to check if the `key` parameter is a list, and if it is, do the above.

**Comment by PabloLec** [comment]
Sure! I didn't think about that. 
Also, I made the name plural, `KEYS_BACKSPACE` as I saw other plural occurences of "key". But maybe it will not be really clear for the dev as to why use a plural name for a single key. Also it will break backward compatibility. I guess I should either just rename it or make an alias, keep the `KEYS` to make it clear it's a list for maintainers but also refer it as `KEY` for users. (?)

**Comment by jwlodek** [comment]
Ah good thing you mentioned that as I didn't even notice :sweat_smile: 

I think keeping it at `KEY_BACKSPACE` without the plural would be best - this way it's more transparent to the user, and won't break BC. Maybe something like `_KEYS_BACKSPACE` as an internal alias would be a good idea as well so it makes sense internally, but for someone using the library, `KEY` singular is more clear imo

**Comment by PabloLec** [comment]
Yeah I'll just drop the "S". I'm not on my usual dev environment right now, I'll wait until tomorrow to make the changes (I don't want to miss any occurence). Just saying in case you want to implement this change in 0.1.4.

**Comment by jwlodek** [comment]
I actually just released 0.1.4, so this will have to wait for the next one. Hope the next release won't take as long, since I have more less ambitious features I want to add, and some bug fixes - no huge logging overhauls or mouse support additions

**Comment by PabloLec** [comment]
Ok, I think this one is good for merge.

**Review by jwlodek — APPROVED** [review]

**Pull request merged**
